### ISSUE TITLE
todo/fix

### ISSUE THREAD

**Issue by mterlyn** [rynmy/balatromod-scripts#1]
### todo
- [ ] detection of balatro install location

### to fix
- [ ] install script is not transferring files onto balatro dir
- [x] uninstallation script removes game directory
